name: Nuitka Poetry from Python
run-name: ${{ github.actor }} using Nuitka on local
on:
  push:
    paths:
      - '.github/workflows/nuitka_poetry.yaml'  # このファイルの変更時にトリガー
      - 'src/using_library_from_pyproject.py'   # 関連するコード変更も許可
      - 'pyproject.toml'   # 関連するコード変更も許可

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-plugin-export
          
        # poetryの依存関係をpipでインストールできるように変換
        # ChiCaRoプロジェクトはpoetryで作成されているため必要。
      - name: Create requirements_pyproject.txt from pyproject.toml
        run: |
          poetry export -f requirements.txt --output requirements_pyproject.txt --without-hashes

        # pipで依存関係をインストール。一時的にpypi.orgへのSSL認証を無視。
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements_pyproject.txt --trusted-host pypi.org
          python -m pip install Nuitka

      - name: Build Executable
        run: |
          python -m nuitka --standalone --output-dir=dist src/using_library_from_pyproject.py 

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} using library from pyproject
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true