name: Nuitka Actions Using Library from Pyproject
run-name: ${{ github.actor }} using library from pyproject
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Create requirements_pyproject.txt from pyproject.toml
        run: |
          poetry export -f requirements_pyproject.txt --output requirements.txt --without-hashes

      - name: Install Dependencies
        run: |
          pip install -r requirements_pyproject.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: using_library_from_pyproject.py
          mode: app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} using library from pyproject
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true