name: Nuitka Actions Read Only File
run-name: ${{ github.actor }} is testing Read Only File

on:
  push:
    paths:
      - '.github/workflows/test_read_only_file.yaml'  # このファイルの変更時にトリガー
      - 'test/read_only_file.py'                     # 関連するファイルが変更されたとき

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: 'test/read_only_file.py'
          mode: app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} read file demo
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true